train_config:
  model_name: "resnet50"
  dataset_name: "cifar10"
  batch_size: 5
  input_size: ['(2,3,224,224)']
  test_size: 2
  dtypes: ['float']
  epoch: 5
  loss_name: "CrossEntropy"
  optimizer: "SGD"
  learning_rate: 0.02
  loss_ground_truth : 2.950969386100769
  eval_ground_truth : 0.998740881321355
  memory_threshold : 0.01


mutation_config:
  mutation_iterations : 20
  save_iterations: 1
  mutation_eval_metric : "origin_diff"
  validation_threshold: 0.01
  output_difference_metric : "DMAD"
