train_config:
  model_name: "yolov4"
  dataset_name: "coco2017yolov4"
  batch_size: 5
  input_size: ['(2,3,416,416)']
  epoch: 2
  test_size: 2
  dtypes: ['float']
  loss_name: "yololoss"
  optimizer: "SGD"
  learning_rate: 0.02
  loss_ground_truth : 2.950969386100769
  eval_ground_truth : 0.998740881321355
  memory_threshold : 1e-2


mutation_config:
  mutation_iterations : 20
  save_iterations: 1
  mutation_eval_metric : "origin_diff"
  validation_threshold: 0.005
  output_difference_metric : "DMAD"
